### ISSUE TITLE
an easier way to get Roman numerals?

### ISSUE THREAD

**Issue by ousia** [jtauber/enchiridion#6]
@jtauber,

I wonder whether this CSS snippet is a simpler way to get Roman numerals:

``` css
div.chapter {
  counter-increment: chapter_roman;
}
h3.chapter_ref:before {
 content: counter(chapter_roman, upper-roman);
}
```

This avoids an extra dependency and also it avoids hard-coded Unicode characters.

_The Unicode Guide_ recommends on its page 853 (https://www.unicode.org/versions/Unicode14.0.0/ch22.pdf#nameddest=G42902):

> **Roman Numerals.** For most purposes, it is preferable to compose the Roman numerals from sequences of the appropriate Latin letters. However, the uppercase and lowercase variants of the Roman numerals through 12, plus L, C, D, and M, have been encoded…

Sorry, but some Roman numbers in special Unicode characters look weird.

Just in case it might help.
